repos:
-   repo: local
    hooks:
    - id: format
      name: mainly isort
      entry: make format
      language: system
      pass_filenames: false
    - id: style-check
      name: Check code style
      entry: black --diff --check cluster examples tests
      language: system
      pass_filenames: false
      types: [python3]
    - id: doc-test
      name: Ensure doc is buildable
      entry: make build-doc
      language: system
      pass_filenames: false


-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--check]
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      args: ["--ignore=E501,E203,F401,W503,W504,E741,F403,F405,F841"]
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: debug-statements
    - id: end-of-file-fixer
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
    - id: blacken-docs
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black
